# 버전 작성 : 도커 컴포즈 버전임
version : "3.7"
#실행할 서비스
services:
  nginx:
    image: nginx:1.24.0
    networks:
      - network
    volumes:
      - /home/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/nginx/media:/data/dumpmedia
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
    depends_on:
      - django
  # 서비스 이름
  django:
    # 사용할 이미지
    image: django_image:3
    networks:
      - network
    volumes:
      - static-volume:/home/webtoon/staticfiles
      - media-volume:/home/webtoon/media
    secrets:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    networks:
      - network
    volumes:
      - mysql-database:/var/lib/mysql
    secrets:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    # 환경변수
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE_FILE=/run/secrets/MYSQL_DATABASE
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD

# 볼륨과 네트워트 설정에 대한 명시
networks:
  network:

volumes:
  static-volume:
  media-volume:
  mysql-database:

secrets:
  DJANGO_SECRET_KEY:
    external: true

  MYSQL_DATABASE:
    external: true
  MYSQL_USER:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true