# Generated by Django 4.1.7 on 2023-03-02 12:14

from django.db import migrations, models
import django.db.models.deletion
import webtoon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(max_length=30, verbose_name='이름')),
                ('auther_create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가 리스트',
            },
        ),
        migrations.CreateModel(
            name='DayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, verbose_name='연재일')),
                ('day_create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '연재일',
                'verbose_name_plural': '연재일 리스트',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10, unique=True, verbose_name='태그')),
                ('tag_create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 리스트',
            },
        ),
        migrations.CreateModel(
            name='WebtoonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_name', models.CharField(max_length=100, unique=True, verbose_name='웹툰')),
                ('webtoon_description', models.CharField(max_length=300, unique=True, verbose_name='설명')),
                ('webtoon_link', models.CharField(max_length=510, unique=True, verbose_name='링크')),
                ('webtoon_img', models.ImageField(storage=webtoon.models.OverwriteStorage, upload_to=webtoon.models.webtoon_img_path, verbose_name='이미지')),
                ('webtoon_end', models.BooleanField(default=False, verbose_name='완결')),
                ('webtoon_adult', models.BooleanField(default=False, verbose_name='성인')),
                ('webtoon_create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('webtoon_auther', models.ManyToManyField(to='webtoon.authermodel', verbose_name='작가')),
                ('webtoon_day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webtoon.daymodel', verbose_name='연재일')),
                ('webtoon_tag', models.ManyToManyField(to='webtoon.tagmodel', verbose_name='태그')),
            ],
            options={
                'verbose_name': '웹툰',
                'verbose_name_plural': '웹툰 리스트',
            },
        ),
        migrations.CreateModel(
            name='BookmarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(max_length=255, verbose_name='유저식별값')),
                ('user_create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('bookmark_webtoon', models.ManyToManyField(blank=True, null=True, to='webtoon.webtoonmodel', verbose_name='북마크')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '유저별 북마크',
            },
        ),
    ]
