# Generated by Django 4.1.7 on 2023-03-10 04:54

from django.db import migrations, models
import django.db.models.deletion
import webtoon.models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_adult',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='성인'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_auther',
            field=models.ManyToManyField(blank=True, null=True, to='webtoon.authermodel', verbose_name='작가'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webtoon.daymodel', verbose_name='연재일'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_description',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_end',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='완결'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_img',
            field=models.ImageField(blank=True, null=True, storage=webtoon.models.OverwriteStorage, upload_to=webtoon.models.webtoon_img_path, verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_link',
            field=models.CharField(blank=True, max_length=510, null=True, unique=True, verbose_name='링크'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_tag',
            field=models.ManyToManyField(blank=True, null=True, to='webtoon.tagmodel', verbose_name='태그'),
        ),
    ]
