# Generated by Django 4.1.7 on 2023-03-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_alter_webtoonmodel_webtoon_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkmodel',
            name='bookmark_webtoon',
            field=models.ManyToManyField(blank=True, to='webtoon.webtoonmodel', verbose_name='북마크'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_auther',
            field=models.ManyToManyField(blank=True, to='webtoon.authermodel', verbose_name='작가'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_tag',
            field=models.ManyToManyField(blank=True, to='webtoon.tagmodel', verbose_name='태그'),
        ),
    ]
