# Generated by Django 4.1.7 on 2023-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0003_alter_bookmarkmodel_bookmark_webtoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_link',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='링크'),
        ),
    ]
