# Generated by Django 4.2 on 2023-04-23 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0004_alter_webtoonmodel_webtoon_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_day', models.CharField(max_length=3, verbose_name='연재일')),
                ('serial_create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '연재일',
                'verbose_name_plural': '연재일 리스트',
            },
        ),
        migrations.RemoveField(
            model_name='webtoonmodel',
            name='webtoon_day',
        ),
        migrations.AlterField(
            model_name='authermodel',
            name='auther_name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_adult',
            field=models.BooleanField(default=False, verbose_name='성인'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_end',
            field=models.BooleanField(default=False, verbose_name='완결'),
        ),
        migrations.AlterField(
            model_name='webtoonmodel',
            name='webtoon_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='링크'),
        ),
        migrations.DeleteModel(
            name='DayModel',
        ),
        migrations.AddField(
            model_name='webtoonmodel',
            name='webtoon_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webtoon.serialmodel', verbose_name='연재일'),
        ),
    ]
